FROM node:20-alpine
WORKDIR /app

# Копируем package.json
COPY package*.json ./

# Устанавливаем зависимости ВКЛЮЧАЯ react-router-dom и axios
RUN npm install && npm install react-router-dom axios --save

# Копируем остальные файлы
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]