spring.application.name=BaseTest

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.types.print.banner=false
spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=true
spring.jpa.database-platform=com.example.hibernate.PgVectorDialect

spring.mail.username=onlineshopkortex@gmail.com
spring.mail.password=knebwfvpomysjsec

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=14
logging.level.root=${LOG_LEVEL:INFO}

cors.allowed-origins=http://localhost:5173,http://localhost:3000

jwt.secret=${JWT}